use jsonschema_schema::{Schema, SchemaValue, SimpleType, TypeValue};
use openergo_server::config::ConfigFile;
use schemars::schema_for;
use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

const SERVER_CONFIG_SCHEMA_PATH: &str = "crates/server/config.schema.json";
const SERVER_CONFIG_DOCS_PATH: &str = "crates/server/config.reference.md";

pub fn generate_config_schema(
    root: &Path,
    mut args: impl Iterator<Item = String>,
) -> Result<(), String> {
    let check = match args.next().as_deref() {
        None => false,
        Some("--check") => true,
        Some(arg) => return Err(format!("unexpected argument {arg:?}")),
    };
    if args.next().is_some() {
        return Err("too many arguments".to_owned());
    }

    let generated = render_server_config_schema()?;
    let schema_path = root.join(SERVER_CONFIG_SCHEMA_PATH);

    if check {
        let current = fs::read_to_string(&schema_path)
            .map_err(|err| format!("read {}: {err}", schema_path.display()))?;
        if current != generated {
            return Err(format!(
                "{} is out of date; run `cargo xtask generate-config-schema`",
                SERVER_CONFIG_SCHEMA_PATH
            ));
        }
    } else {
        fs::write(&schema_path, generated)
            .map_err(|err| format!("write {}: {err}", schema_path.display()))?;
    }

    Ok(())
}

pub fn generate_config_docs(
    root: &Path,
    mut args: impl Iterator<Item = String>,
) -> Result<(), String> {
    let mut check = false;
    let mut output_path = root.join(SERVER_CONFIG_DOCS_PATH);
    let mut schema_path = None;

    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--check" => check = true,
            "--output" => {
                let Some(path) = args.next() else {
                    return Err("--output requires a path".to_owned());
                };
                output_path = resolve_path(root, path);
            }
            "--schema" => {
                let Some(path) = args.next() else {
                    return Err("--schema requires a path".to_owned());
                };
                schema_path = Some(resolve_path(root, path));
            }
            _ => return Err(format!("unexpected argument {arg:?}")),
        }
    }

    let schema_json = match schema_path {
        Some(path) => fs::read_to_string(&path)
            .map_err(|err| format!("read schema {}: {err}", path.display()))?,
        None => render_server_config_schema()?,
    };
    let schema = serde_json::from_str::<Schema>(&schema_json)
        .map_err(|err| format!("parse server config schema json: {err}"))?;
    let generated = render_config_docs(&schema)?;

    if check {
        let current = fs::read_to_string(&output_path)
            .map_err(|err| format!("read {}: {err}", output_path.display()))?;
        if current != generated {
            return Err(format!(
                "{} is out of date; run `cargo xtask generate-config-docs`",
                display_path(root, &output_path)
            ));
        }
    } else {
        fs::write(&output_path, generated)
            .map_err(|err| format!("write {}: {err}", output_path.display()))?;
    }

    Ok(())
}

fn render_server_config_schema() -> Result<String, String> {
    let schema = schema_for!(ConfigFile);
    let mut json = serde_json::to_string_pretty(&schema)
        .map_err(|err| format!("serialize server config schema: {err}"))?;
    json.push('\n');
    Ok(json)
}

fn render_config_docs(schema: &Schema) -> Result<String, String> {
    let mut out = String::new();
    out.push_str("# Server TOML Config Reference\n\n");
    out.push_str("_Generated by `cargo xtask generate-config-docs`; do not edit by hand._\n\n");

    if let Some(description) = schema.description() {
        out.push_str(&paragraph(description));
        out.push('\n');
    }

    for (name, property_schema) in &schema.properties {
        render_property_section(schema, property_schema, name, &mut out)?;
    }

    Ok(out)
}

fn render_property_section(
    root: &Schema,
    schema: &SchemaValue,
    toml_path: &str,
    out: &mut String,
) -> Result<(), String> {
    let resolved = resolve_schema(root, schema)?;
    if let Some(value_schema) = additional_properties_schema(resolved) {
        let resolved_value = resolve_schema(root, value_schema)?;
        if is_object_schema(resolved_value) && !resolved_value.properties.is_empty() {
            let description = schema.as_schema().and_then(Schema::description);
            render_table_section(root, resolved_value, toml_path, description, out)?;
        } else {
            render_scalar_map_section(root, schema, value_schema, toml_path, out)?;
        }
    } else if is_object_schema(resolved) && !resolved.properties.is_empty() {
        let description = schema.as_schema().and_then(Schema::description);
        render_table_section(root, resolved, toml_path, description, out)?;
    }
    Ok(())
}

fn render_table_section(
    root: &Schema,
    schema: &Schema,
    toml_path: &str,
    description: Option<&str>,
    out: &mut String,
) -> Result<(), String> {
    out.push_str(&format!(
        "{} `[{toml_path}]`\n\n",
        heading_marker(toml_path)
    ));
    render_descriptions(out, [description, schema.description()]);

    let required = required_fields(schema);
    render_fields_table(root, schema.properties.iter(), &required, out)?;

    for (name, property_schema) in &schema.properties {
        let resolved = resolve_schema(root, property_schema)?;
        let child_path = if let Some(value_schema) = additional_properties_schema(resolved) {
            let value_schema = resolve_schema(root, value_schema)?;
            if is_object_schema(value_schema) {
                format!("{toml_path}.{name}.<name>")
            } else {
                format!("{toml_path}.{name}")
            }
        } else {
            format!("{toml_path}.{name}")
        };
        render_property_section(root, property_schema, &child_path, out)?;
    }

    Ok(())
}

fn render_scalar_map_section(
    root: &Schema,
    map_schema: &SchemaValue,
    value_schema: &SchemaValue,
    toml_path: &str,
    out: &mut String,
) -> Result<(), String> {
    out.push_str(&format!(
        "{} `[{toml_path}]`\n\n",
        heading_marker(toml_path)
    ));
    render_descriptions(
        out,
        [
            schema_value_description(root, map_schema)?,
            schema_value_description(root, value_schema)?,
        ],
    );
    out.push_str("| Key | Type |\n");
    out.push_str("| --- | --- |\n");
    out.push_str(&format!(
        "| `<name>` | {} |\n\n",
        markdown_code(&type_label(root, value_schema)?)
    ));
    Ok(())
}

fn render_fields_table<'a>(
    root: &Schema,
    properties: impl Iterator<Item = (&'a String, &'a SchemaValue)>,
    required: &BTreeSet<String>,
    out: &mut String,
) -> Result<(), String> {
    out.push_str("| Key | Type | Required | Description |\n");
    out.push_str("| --- | --- | --- | --- |\n");
    for (name, schema) in properties {
        if renders_child_table(root, schema)? {
            continue;
        }
        let description = schema_value_description(root, schema)?
            .map(markdown_text)
            .unwrap_or_default();
        let required = if required.contains(name) { "yes" } else { "no" };
        out.push_str(&format!(
            "| `{name}` | {} | {required} | {description} |\n",
            markdown_code(&type_label(root, schema)?)
        ));
    }
    out.push('\n');
    Ok(())
}

fn renders_child_table(root: &Schema, schema: &SchemaValue) -> Result<bool, String> {
    let resolved = resolve_schema(root, schema)?;
    Ok(additional_properties_schema(resolved).is_some())
}

fn type_label(root: &Schema, schema: &SchemaValue) -> Result<String, String> {
    let schema = resolve_schema(root, schema)?;

    if let Some(values) = enum_values(schema) {
        return Ok(values.join(" | "));
    }

    if let Some(items) = schema.items.as_deref() {
        return Ok(format!("array of {}", type_label(root, items)?));
    }

    if let Some(value_schema) = additional_properties_schema(schema) {
        let value_schema = resolve_schema(root, value_schema)?;
        if is_object_schema(value_schema) {
            return Ok("table map".to_owned());
        }
        return Ok(format!(
            "map of {}",
            type_label(root, &SchemaValue::Schema(Box::new(value_schema.clone())))?
        ));
    }

    if is_object_schema(schema) {
        return Ok("table".to_owned());
    }

    Ok(schema
        .type_
        .as_ref()
        .map(type_label_from_type)
        .unwrap_or_else(|| "value".to_owned()))
}

fn required_fields(schema: &Schema) -> BTreeSet<String> {
    schema.required_set().iter().cloned().collect()
}

fn resolve_schema<'a>(root: &'a Schema, schema: &'a SchemaValue) -> Result<&'a Schema, String> {
    let schema = non_null_schema(schema);
    let schema = schema
        .as_schema()
        .ok_or_else(|| "expected object schema".to_owned())?;
    let Some(reference) = schema.ref_.as_deref() else {
        return Ok(schema);
    };
    let def_name = reference
        .strip_prefix("#/$defs/")
        .ok_or_else(|| format!("unsupported schema reference {reference:?}"))?;
    root.defs
        .as_ref()
        .and_then(|defs| defs.get(def_name))
        .and_then(SchemaValue::as_schema)
        .ok_or_else(|| format!("schema reference {reference:?} was not found"))
}

fn non_null_schema(schema: &SchemaValue) -> &SchemaValue {
    schema
        .as_schema()
        .and_then(|schema| schema.any_of.as_ref())
        .and_then(|schemas| schemas.iter().find(|schema| !is_null_schema(schema)))
        .unwrap_or(schema)
}

fn is_null_schema(schema: &SchemaValue) -> bool {
    schema
        .as_schema()
        .and_then(|schema| schema.type_.as_ref())
        .is_some_and(type_has_null)
}

fn is_object_schema(schema: &Schema) -> bool {
    schema.type_.as_ref().is_some_and(type_has_object)
}

fn additional_properties_schema(schema: &Schema) -> Option<&SchemaValue> {
    schema
        .additional_properties
        .as_deref()
        .filter(|value| matches!(value, SchemaValue::Schema(_)))
}

fn type_has_null(type_value: &TypeValue) -> bool {
    type_value_contains(type_value, SimpleType::Null)
}

fn type_has_object(type_value: &TypeValue) -> bool {
    type_value_contains(type_value, SimpleType::Object)
}

fn type_value_contains(type_value: &TypeValue, needle: SimpleType) -> bool {
    match type_value {
        TypeValue::Single(kind) => *kind == needle,
        TypeValue::Union(kinds) => kinds.contains(&needle),
    }
}

fn type_label_from_type(type_value: &TypeValue) -> String {
    match type_value {
        TypeValue::Single(kind) => kind.to_string(),
        TypeValue::Union(kinds) => kinds
            .iter()
            .filter(|kind| **kind != SimpleType::Null)
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(" | "),
    }
}

fn enum_values(schema: &Schema) -> Option<Vec<String>> {
    schema
        .one_of
        .as_ref()?
        .iter()
        .map(|variant| {
            variant
                .as_schema()?
                .const_
                .as_ref()?
                .as_str()
                .map(|value| format!("\"{value}\""))
        })
        .collect::<Option<Vec<_>>>()
}

fn schema_value_description<'a>(
    root: &'a Schema,
    schema: &'a SchemaValue,
) -> Result<Option<&'a str>, String> {
    if let Some(description) = schema.as_schema().and_then(Schema::description) {
        return Ok(Some(description));
    }
    Ok(resolve_schema(root, schema)?.description())
}

fn paragraph(text: &str) -> String {
    format!("{}\n", markdown_text(text))
}

fn render_descriptions<'a>(
    out: &mut String,
    descriptions: impl IntoIterator<Item = Option<&'a str>>,
) {
    let mut rendered = Vec::new();
    for description in descriptions.into_iter().flatten().map(markdown_text) {
        if !rendered.contains(&description) {
            rendered.push(description);
        }
    }
    for description in rendered {
        out.push_str(&paragraph(&description));
        out.push('\n');
    }
}

fn markdown_text(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn markdown_code(text: &str) -> String {
    format!("`{}`", text.replace('`', "\\`").replace('|', "\\|"))
}

fn heading_marker(toml_path: &str) -> &'static str {
    if toml_path.contains('.') { "###" } else { "##" }
}

fn resolve_path(root: &Path, path: String) -> PathBuf {
    let path = PathBuf::from(path);
    if path.is_absolute() {
        path
    } else {
        root.join(path)
    }
}

fn display_path(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .display()
        .to_string()
}
