// @generated by `cargo xtask generate-fdr-schema`; do not edit by hand.

// ---- fdr_session ----

impl FdrTable for FdrSession {
    const NAME: &'static str = "fdr_session";
    const CREATE_TABLE: &'static str = r"CREATE TABLE IF NOT EXISTS fdr_session (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_uuid BLOB NOT NULL UNIQUE,
    started_at INTEGER NOT NULL,
    app_state_id BLOB NOT NULL,
    app_state_basis INTEGER NOT NULL,
    app_state_generation INTEGER NOT NULL,
    activity_total_baseline_ns INTEGER NOT NULL
) STRICT;";
    const CREATE_INDEX: &'static [&'static str] = &[];
    const INSERT: &'static str = r"INSERT INTO fdr_session (
    session_uuid, started_at, app_state_id, app_state_basis,
    app_state_generation, activity_total_baseline_ns
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6
)";
    fn values(&self, _session_id: i64) -> Vec<Value> {
        vec![
            uuid_value(self.session_uuid),
            ts_value(self.started_at),
            uuid_value(self.app_state_id),
            Value::Integer(self.app_state_basis as i64),
            Value::Integer(self.app_state_generation as i64),
            dur_value(self.activity_total_baseline),
        ]
    }
}
// ---- usage_credit ----

impl FdrTable for UsageCreditBucket {
    const NAME: &'static str = "usage_credit";
    const CREATE_TABLE: &'static str = r"CREATE TABLE IF NOT EXISTS usage_credit (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id INTEGER NOT NULL REFERENCES fdr_session(id),
    bucket_start INTEGER NOT NULL,
    bucket_end INTEGER NOT NULL,
    increment_count INTEGER NOT NULL,
    u_click_count INTEGER NOT NULL,
    u_drag_ns INTEGER NOT NULL,
    u_key_count INTEGER NOT NULL,
    u_scroll_count INTEGER NOT NULL,
    u_left_shift_ns INTEGER NOT NULL,
    u_left_ctrl_ns INTEGER NOT NULL,
    u_left_alt_ns INTEGER NOT NULL,
    u_left_meta_ns INTEGER NOT NULL,
    u_right_shift_ns INTEGER NOT NULL,
    u_right_ctrl_ns INTEGER NOT NULL,
    u_right_alt_ns INTEGER NOT NULL,
    u_right_meta_ns INTEGER NOT NULL,
    u_active_ns INTEGER NOT NULL,
    cb_click REAL NOT NULL,
    cb_drag REAL NOT NULL,
    cb_key REAL NOT NULL,
    cb_scroll REAL NOT NULL,
    cb_left_shift REAL NOT NULL,
    cb_left_ctrl REAL NOT NULL,
    cb_left_alt REAL NOT NULL,
    cb_left_meta REAL NOT NULL,
    cb_right_shift REAL NOT NULL,
    cb_right_ctrl REAL NOT NULL,
    cb_right_alt REAL NOT NULL,
    cb_right_meta REAL NOT NULL,
    cx_click REAL NOT NULL,
    cx_drag REAL NOT NULL,
    cx_key REAL NOT NULL,
    cx_scroll REAL NOT NULL,
    cx_left_shift REAL NOT NULL,
    cx_left_ctrl REAL NOT NULL,
    cx_left_alt REAL NOT NULL,
    cx_left_meta REAL NOT NULL,
    cx_right_shift REAL NOT NULL,
    cx_right_ctrl REAL NOT NULL,
    cx_right_alt REAL NOT NULL,
    cx_right_meta REAL NOT NULL,
    max_increment_key_count INTEGER NOT NULL,
    max_increment_click_count INTEGER NOT NULL,
    max_increment_scroll_count INTEGER NOT NULL,
    max_increment_total_credit REAL NOT NULL,
    sum_increment_total_credit_squared REAL NOT NULL,
    active_increment_count INTEGER NOT NULL,
    observed_duration_ns INTEGER NOT NULL
) STRICT;";
    const CREATE_INDEX: &'static [&'static str] = &[
        r"CREATE INDEX IF NOT EXISTS usage_credit_session_bucket_start ON usage_credit(session_id, bucket_start);",
        r"CREATE INDEX IF NOT EXISTS usage_credit_bucket_start ON usage_credit(bucket_start);",
    ];
    const INSERT: &'static str = r"INSERT INTO usage_credit (
    session_id, bucket_start, bucket_end, increment_count,
    u_click_count, u_drag_ns, u_key_count, u_scroll_count,
    u_left_shift_ns, u_left_ctrl_ns, u_left_alt_ns, u_left_meta_ns,
    u_right_shift_ns, u_right_ctrl_ns, u_right_alt_ns, u_right_meta_ns,
    u_active_ns, cb_click, cb_drag, cb_key,
    cb_scroll, cb_left_shift, cb_left_ctrl, cb_left_alt,
    cb_left_meta, cb_right_shift, cb_right_ctrl, cb_right_alt,
    cb_right_meta, cx_click, cx_drag, cx_key,
    cx_scroll, cx_left_shift, cx_left_ctrl, cx_left_alt,
    cx_left_meta, cx_right_shift, cx_right_ctrl, cx_right_alt,
    cx_right_meta, max_increment_key_count, max_increment_click_count, max_increment_scroll_count,
    max_increment_total_credit, sum_increment_total_credit_squared, active_increment_count, observed_duration_ns
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8,
    ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16,
    ?17, ?18, ?19, ?20, ?21, ?22, ?23, ?24,
    ?25, ?26, ?27, ?28, ?29, ?30, ?31, ?32,
    ?33, ?34, ?35, ?36, ?37, ?38, ?39, ?40,
    ?41, ?42, ?43, ?44, ?45, ?46, ?47, ?48
)";
    fn values(&self, session_id: i64) -> Vec<Value> {
        vec![
            Value::Integer(session_id),
            ts_value(self.bucket_start),
            ts_value(self.bucket_end),
            Value::Integer(self.increment_count as i64),
            Value::Integer(self.u_click_count as i64),
            dur_value(self.u_drag),
            Value::Integer(self.u_key_count as i64),
            Value::Integer(self.u_scroll_count as i64),
            dur_value(self.u_left_shift),
            dur_value(self.u_left_ctrl),
            dur_value(self.u_left_alt),
            dur_value(self.u_left_meta),
            dur_value(self.u_right_shift),
            dur_value(self.u_right_ctrl),
            dur_value(self.u_right_alt),
            dur_value(self.u_right_meta),
            dur_value(self.u_active),
            credit_value(self.cb_click),
            credit_value(self.cb_drag),
            credit_value(self.cb_key),
            credit_value(self.cb_scroll),
            credit_value(self.cb_left_shift),
            credit_value(self.cb_left_ctrl),
            credit_value(self.cb_left_alt),
            credit_value(self.cb_left_meta),
            credit_value(self.cb_right_shift),
            credit_value(self.cb_right_ctrl),
            credit_value(self.cb_right_alt),
            credit_value(self.cb_right_meta),
            credit_value(self.cx_click),
            credit_value(self.cx_drag),
            credit_value(self.cx_key),
            credit_value(self.cx_scroll),
            credit_value(self.cx_left_shift),
            credit_value(self.cx_left_ctrl),
            credit_value(self.cx_left_alt),
            credit_value(self.cx_left_meta),
            credit_value(self.cx_right_shift),
            credit_value(self.cx_right_ctrl),
            credit_value(self.cx_right_alt),
            credit_value(self.cx_right_meta),
            Value::Integer(self.max_increment_key_count as i64),
            Value::Integer(self.max_increment_click_count as i64),
            Value::Integer(self.max_increment_scroll_count as i64),
            credit_value(self.max_increment_total_credit),
            credit_value(self.sum_increment_total_credit_squared),
            Value::Integer(self.active_increment_count as i64),
            dur_value(self.observed_duration),
        ]
    }
}
// ---- activity ----

impl FdrTable for ActivityBucket {
    const NAME: &'static str = "activity";
    const CREATE_TABLE: &'static str = r"CREATE TABLE IF NOT EXISTS activity (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id INTEGER NOT NULL REFERENCES fdr_session(id),
    bucket_start INTEGER NOT NULL,
    bucket_end INTEGER NOT NULL,
    activity_delta_ns INTEGER NOT NULL
) STRICT;";
    const CREATE_INDEX: &'static [&'static str] = &[
        r"CREATE INDEX IF NOT EXISTS activity_session_bucket_start ON activity(session_id, bucket_start);",
        r"CREATE INDEX IF NOT EXISTS activity_bucket_start ON activity(bucket_start);",
    ];
    const INSERT: &'static str = r"INSERT INTO activity (
    session_id, bucket_start, bucket_end, activity_delta_ns
) VALUES (
    ?1, ?2, ?3, ?4
)";
    fn values(&self, session_id: i64) -> Vec<Value> {
        vec![
            Value::Integer(session_id),
            ts_value(self.bucket_start),
            ts_value(self.bucket_end),
            dur_value(self.activity_delta),
        ]
    }
}
// ---- credit_window_state ----

impl FdrTable for CreditWindowState {
    const NAME: &'static str = "credit_window_state";
    const CREATE_TABLE: &'static str = r"CREATE TABLE IF NOT EXISTS credit_window_state (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id INTEGER NOT NULL REFERENCES fdr_session(id),
    recorded_at INTEGER NOT NULL,
    rest_credit_total REAL NOT NULL,
    break_credit_total REAL NOT NULL,
    day_credit_total REAL NOT NULL
) STRICT;";
    const CREATE_INDEX: &'static [&'static str] = &[
        r"CREATE INDEX IF NOT EXISTS credit_window_state_session_recorded_at ON credit_window_state(session_id, recorded_at);",
        r"CREATE INDEX IF NOT EXISTS credit_window_state_recorded_at ON credit_window_state(recorded_at);",
    ];
    const INSERT: &'static str = r"INSERT INTO credit_window_state (
    session_id, recorded_at, rest_credit_total, break_credit_total,
    day_credit_total
) VALUES (
    ?1, ?2, ?3, ?4, ?5
)";
    fn values(&self, session_id: i64) -> Vec<Value> {
        vec![
            Value::Integer(session_id),
            ts_value(self.recorded_at),
            Value::Real(self.rest_credit_total),
            Value::Real(self.break_credit_total),
            Value::Real(self.day_credit_total),
        ]
    }
}
// ---- pain_change ----

impl FdrTable for PainChange {
    const NAME: &'static str = "pain_change";
    const CREATE_TABLE: &'static str = r"CREATE TABLE IF NOT EXISTS pain_change (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id INTEGER NOT NULL REFERENCES fdr_session(id),
    recorded_at INTEGER NOT NULL,
    label TEXT NOT NULL,
    bias TEXT NOT NULL,
    ratio REAL NOT NULL,
    last_updated INTEGER NOT NULL
) STRICT;";
    const CREATE_INDEX: &'static [&'static str] = &[
        r"CREATE INDEX IF NOT EXISTS pain_change_session_recorded_at ON pain_change(session_id, recorded_at);",
        r"CREATE INDEX IF NOT EXISTS pain_change_label_recorded_at ON pain_change(label, recorded_at);",
    ];
    const INSERT: &'static str = r"INSERT INTO pain_change (
    session_id, recorded_at, label, bias,
    ratio, last_updated
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6
)";
    fn values(&self, session_id: i64) -> Vec<Value> {
        vec![
            Value::Integer(session_id),
            ts_value(self.recorded_at),
            text_value(&self.label),
            text_value(self.bias.as_str()),
            Value::Real(self.ratio),
            ts_value(self.last_updated),
        ]
    }
}
// ---- credit_limit_change ----

impl FdrTable for CreditLimitChange {
    const NAME: &'static str = "credit_limit_change";
    const CREATE_TABLE: &'static str = r"CREATE TABLE IF NOT EXISTS credit_limit_change (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id INTEGER NOT NULL REFERENCES fdr_session(id),
    recorded_at INTEGER NOT NULL,
    rest REAL NOT NULL,
    breaks REAL NOT NULL,
    day REAL NOT NULL
) STRICT;";
    const CREATE_INDEX: &'static [&'static str] = &[
        r"CREATE INDEX IF NOT EXISTS credit_limit_change_session_recorded_at ON credit_limit_change(session_id, recorded_at);",
        r"CREATE INDEX IF NOT EXISTS credit_limit_change_recorded_at ON credit_limit_change(recorded_at);",
    ];
    const INSERT: &'static str = r"INSERT INTO credit_limit_change (
    session_id, recorded_at, rest, breaks,
    day
) VALUES (
    ?1, ?2, ?3, ?4, ?5
)";
    fn values(&self, session_id: i64) -> Vec<Value> {
        vec![
            Value::Integer(session_id),
            ts_value(self.recorded_at),
            Value::Real(self.rest),
            Value::Real(self.breaks),
            Value::Real(self.day),
        ]
    }
}
// ---- credit_event ----

impl FdrTable for CreditEventRecord {
    const NAME: &'static str = "credit_event";
    const CREATE_TABLE: &'static str = r"CREATE TABLE IF NOT EXISTS credit_event (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id INTEGER NOT NULL REFERENCES fdr_session(id),
    recorded_at INTEGER NOT NULL,
    kind TEXT NOT NULL,
    event TEXT NOT NULL,
    level INTEGER,
    rest_utilization REAL NOT NULL,
    break_utilization REAL NOT NULL,
    day_utilization REAL NOT NULL
) STRICT;";
    const CREATE_INDEX: &'static [&'static str] = &[
        r"CREATE INDEX IF NOT EXISTS credit_event_session_recorded_at ON credit_event(session_id, recorded_at);",
        r"CREATE INDEX IF NOT EXISTS credit_event_recorded_at ON credit_event(recorded_at);",
    ];
    const INSERT: &'static str = r"INSERT INTO credit_event (
    session_id, recorded_at, kind, event,
    level, rest_utilization, break_utilization, day_utilization
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8
)";
    fn values(&self, session_id: i64) -> Vec<Value> {
        vec![
            Value::Integer(session_id),
            ts_value(self.recorded_at),
            text_value(self.kind.as_str()),
            text_value(self.event.as_str()),
            opt_u8_value(self.level),
            Value::Real(self.rest_utilization),
            Value::Real(self.break_utilization),
            Value::Real(self.day_utilization),
        ]
    }
}
