name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Nothing but Nix
        uses: wimpysworld/nothing-but-nix@v10
      - uses: actions/checkout@v4
      - name: Check Inputs
        uses: DeterminateSystems/flake-checker-action@v13
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3
        with:
          extra-conf: |
            build-dir = /nix/build
      - name: Use Fenix binary cache
        uses: cachix/cachix-action@v16
        with:
          name: fenix
      - uses: DeterminateSystems/magic-nix-cache-action@v14
        with:
          use-flakehub: false
          use-gha-cache: enabled
      - name: Check Flake
        run: nix flake check
