name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - name: Nothing but Nix
        uses: wimpysworld/nothing-but-nix@v10
      - uses: actions/checkout@v4
      - name: Check Inputs
        uses: DeterminateSystems/flake-checker-action@main
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3
      - name: Check Flake
        run: nix flake check
